[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "poppler"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender1", "libgomp1"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "python app.py"

[variables]
LD_PRELOAD = "/usr/lib/x86_64-linux-gnu/libgomp.so.1"