[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements_railway.txt"
]

[start]
cmd = "python app.py"